### ISSUE TITLE
Set up graphql database

### ISSUE THREAD

**Issue by mrsdno** [mrsdno/poke-app#7]
Set up the graphql database

**Comment by Arankin7** [comment]
**User :** 
* has many teams
* username
* email
* password

**Team:** 
* has many (6) pokemon
* belongs to One user
* Pokemon in the Team
* 
**Pokemon:** 
* teamId
* name
* height
* weight
* type
* img

**Comment by Arankin7** [comment]
Server is set up and working.  Will Start working on Models/Schemas followed by Queries and Mutations

**Comment by Arankin7** [comment]
Queries for 'Me', 'Users', 'User' are functinal.  
Mutations for 'addUser' and 'login' are functional.

**Comment by Arankin7** [comment]
Queries for 'Teams', 'Team'(by ID), and 'myFavTeams'
Mutations for 'addTeam'

**Comment by Arankin7** [comment]
Mutation for Adding pokemon to team works.  
Just have to iron out the kinks when implementing the PokeApi calls.
